CREATE TABLE customers (
  "id" SERIAL PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "name" VARCHAR(30) NOT NULL,
  "email" VARCHAR(30) NOT NULL,
  "password" VARCHAR(30) NOT NULL,
  "phone_number" VARCHAR(30),
  "license_number" VARCHAR(30) NOT NULL,
  "city" VARCHAR(30)
);

CREATE TABLE agencies (
  "id" SERIAL PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "name" VARCHAR(30) NOT NULL,
  "email" VARCHAR(30) NOT NULL,
  "password" VARCHAR(30) NOT NULL,
  "phone_number" VARCHAR(30),
  "city" VARCHAR(30)
);

CREATE TABLE cars (
  "id" SERIAL PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "model" VARCHAR(30) NOT NULL,
  "seating_capacity" int NOT NULL,
  "rent" int NOT NULL,
  "agency_id" INTEGER NOT NULL REFERENCES agencies(id)
)

CREATE TABLE rent (
  "id" SERIAL PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "days" INTEGER NOT NULL,
  "car_id" INTEGER NOT NULL REFERENCES cars(id),
  "customer_id" INTEGER NOT NULL REFERENCES customers(id)
)
