CREATE TABLE admins (
  "id" SERIAL PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "admin_name" VARCHAR(30) NOT NULL,
  "username" VARCHAR(40) NOT NULL,
  "email" VARCHAR(40) NOT NULL,
  "password" VARCHAR(50)
);

CREATE TABLE books (
  "id" SERIAL PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "book_title" VARCHAR(50) NOT NULL,
  "author" VARCHAR(50) NOT NULL,
  "publisher_name" VARCHAR(50) NOT NULL,
  "categories" VARCHAR(50) NOT NULL,
  "call_number" VARCHAR(50) NOT NULL
);

CREATE TABLE students (
  "id" SERIAL PRIMARY KEY,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "name" VARCHAR(30) NOT NULL,
  "email" VARCHAR(30) NOT NULL,
  "department" VARCHAR(30) NOT NULL,
  "phone_number" VARCHAR(30) NOT NULL
);

CREATE TABLE borrow (
  "id" SERIAL PRIMARY KEY,
  "borrowed_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "returned_at" TIMESTAMP WITH TIME ZONE,
  "student_id" INTEGER NOT NULL REFERENCES students(id),
  "book_id" INTEGER NOT NULL REFERENCES books(id)
);